#!/bin/sh
#
# curls the last quakes in the world and re-checks it every five seconds to see
# if anything else happens.
#
# POSSIBLE BUG: if it's a really huge earthquake that rips the Earth's crust
# and/or the fabric of space-time in half, this script could be interrupted
# prior to entering the next loop (perhaps my living room just exploded, for
# example).

url='http://earthquake.usgs.gov/earthquakes/catalogs/eqs1hour-M0.txt'
chsum1=`curl --silent $url | sed -n 2p | md5`
chsum2=$chsum1

while [ 1 ]
do
  chsum2=`curl --silent $url | sed -n 2p`
  if [ "$chsum2" != "" ]
  then
    echo $chsum2
    chsum2=`echo $chsum2 | md5`
    if [ "$chsum1" == "$chsum2" ]
    then
      echo "None yet! We're still alive!"
    else
      echo "Holy shit! A fucking earthquake!"
      say "Holy shit! A fucking earthquake!"
      cd 2-vagrant && vagrant up
      exit 0
    fi
  else
    echo "None yet! We're still alive!"
  fi
  sleep 5
done