Vagrant::Config.run do |config|
  config.vm.box     = "base"

  # mount the entire project in /vagranception
  config.vm.share_folder "vagranception", "/vagranception", "../"

  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = "cookbooks"
    chef.add_recipe "run"
  end
end
